---
- hosts: all
  remote_user: root
  tasks:
   - name: Update Packet
     shell: apt-get update
     
   - name: Install Curl
     become: yes
     apt: pkg=curl state=latest update_cache=true
     
   - name: Enable UFW and open port 80,8080,1834
     shell: service ufw start
     shell: ufw allow 80
     shell: ufw allow 8080
     shell: ufw allow 1834
     
   - name:Config SSH
     lineinfile:
                dest=/etc/ssh/ssh_config
                regexp='#   Port 22'
                line='Port 1834'
                state=present
                
   - name: Restart SSH + UFW
     shell: service ssh restart
     shell: service ufw restart
     
   - name: Reboot machine
     shell: reboot
     
     
                
